In [72]:
import ipywidgets as widgets
import pandas as pd
import numpy as np
import psycopg2
import bqplot
import os

In [73]:
os.environ['POSTGRES_USER']
os.environ['POSTGRES_PASS']
host, port = os.environ['POSTGRES_ADDR'].split(':')

In [74]:
connection_config = {
    'user': os.environ['POSTGRES_USER'],
    'password': os.environ['POSTGRES_PASS'],
    'host': host,
    'port': port,
    'database': 'postgres',
}
connection_config

{'user': 'postgres',
 'password': 'putsomesecretpasswordhere',
 'host': 'postgres',
 'port': '5432',
 'database': 'postgres'}

In [75]:
sql = r'SELECT * FROM game_events;'


with psycopg2.connect(**connection_config) as conn:
    df = pd.read_sql_query(sql, conn)

pd.set_option("display.max_colwidth", 120)
df[df.iloc[:, -2] == 1]

,event_id,user_id,game_id,event_time,event_type,payload
4,6,NaN,1,1630586994,1,"{'Map': 0, 'Region': 0, 'LobbyCode': 'BKAUIF'}"
47,52,NaN,6,1630590215,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'YIZCHF'}"
86,98,NaN,12,1630593229,1,"{'Map': 4, 'Region': 1, 'LobbyCode': 'LWRYFF'}"
106,120,NaN,14,1630759016,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'KDKSDF'}"
168,182,NaN,17,1630762641,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'KDKSDF'}"
193,208,NaN,18,1630764706,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'HXONCF'}"
236,250,NaN,20,1630767331,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'HXONCF'}"
249,263,NaN,21,1631195672,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'HLSPNF'}"
272,286,NaN,22,1631196953,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'HLSPNF'}"
338,353,NaN,26,1631796769,1,"{'Map': 0, 'Region': 0, 'LobbyCode': 'CDHYVF'}"
406,422,NaN,28,1631801362,1,"{'Map': 0, 'Region': 0, 'LobbyCode': 'CDHYVF'}"
447,464,NaN,29,1631804296,1,"{'Map': 0, 'Region': 0, 'LobbyCode': 'CDHYVF'}"
453,470,NaN,30,1632399624,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
506,523,NaN,32,1632403769,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
526,544,NaN,33,1632405408,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
548,567,NaN,34,1632407187,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
561,581,NaN,35,1632408154,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
587,607,NaN,36,1632410072,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
613,633,NaN,38,1632581463,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
629,649,NaN,39,1632582210,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
630,672,NaN,40,1632584017,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
665,690,NaN,41,1632585215,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
694,719,NaN,42,1632586713,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
708,744,NaN,44,1633006409,1,"{'Map': 4, 'Region': 1, 'LobbyCode': 'JCYQKF'}"
736,764,NaN,45,1633007593,1,"{'Map': 4, 'Region': 1, 'LobbyCode': 'JCYQKF'}"
747,776,NaN,46,1633008217,1,"{'Map': 4, 'Region': 1, 'LobbyCode': 'JCYQKF'}"
758,787,NaN,48,1633012418,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'EDXSVF'}"

In [76]:
table_list = ['game_events', 'games', 'guilds', 'users', 'users_games']
df_dict_ = {}

for tbl in table_list:
    sql = f'SELECT * FROM {tbl};'
    with psycopg2.connect(**connection_config) as conn:
        df_dict_[tbl] = pd.read_sql_query(sql, conn)

df_dict_

{'game_events':      event_id  user_id  game_id  event_time  event_type  \
 0           1      NaN        1  1630586698           2
 1           2      NaN        1  1630586927           3
 2           3      NaN        1  1630586985           2
 3           5      NaN        1  1630586994           2
 4           6      NaN        1  1630586994           1
 ..        ...      ...      ...         ...         ...
 809       640      NaN       39  1632581975           3
 810       658      NaN       40  1632582986           3
 811       677      NaN       41  1632584490           3
 812       769      NaN       46  1633008022           3
 813       795      NaN       49  1633012617           3

                                                                                   payload
 0                                                                                       1
 1    {'Name': 'Gladpie', 'Color': 14, 'Action': 5, 'IsDead': False, 'Disconnected': True}
 2                                                                                       4
 3                                                                                       0
 4                                          {'Map': 0, 'Region': 0, 'LobbyCode': 'BKAUIF'}
 ..                                                                                    ...
 809       {'Name': 'シン', 'Color': 0, 'Action': 6, 'IsDead': False, 'Disconnected': False}
 810        {'Name': 'シン', 'Color': 0, 'Action': 2, 'IsDead': True, 'Disconnected': False}
 811        {'Name': 'シン', 'Color': 0, 'Action': 2, 'IsDead': True, 'Disconnected': False}
 812        {'Name': 'シン', 'Color': 0, 'Action': 2, 'IsDead': True, 'Disconnected': False}
 813        {'Name': 'シン', 'Color': 0, 'Action': 2, 'IsDead': True, 'Disconnected': False}

 [814 rows x 6 columns],
 'games':     game_id      guild_id connect_code  start_time  win_type    end_time
 0         1  8.458990e+17     7BB09AC8  1630586698         3  1630586994
 1         2  8.458990e+17     7BB09AC8  1630587294         0  1630587711
 2         3  8.458990e+17     7BB09AC8  1630587871         2  1630588211
 3         4  8.458990e+17     663648A9  1630588929         0  1630589199
 4         5  8.458990e+17     663648A9  1630589499         3  1630589545
 5         6  8.458990e+17     663648A9  1630589741         2  1630590215
 6         7  8.458990e+17     663648A9  1630590464         3  1630590488
 7         8  8.458990e+17     663648A9  1630590527         2  1630590922
 8         9  8.458990e+17     663648A9  1630591185         3  1630591724
 9        10  8.458990e+17     663648A9  1630592010         0  1630592192
 10       11  8.458990e+17     663648A9  1630592236         3  1630592476
 11       12  8.458990e+17     663648A9  1630592659         2  1630593229
 12       13  8.458990e+17     A0F9543B  1630757828         0  1630758460
 13       14  8.458990e+17     A0F9543B  1630758594         4  1630759016
 14       15  8.458990e+17     A0F9543B  1630759311         3  1630760188
 15       16  8.458990e+17     A0F9543B  1630760320         0  1630761147
 16       17  8.458990e+17     A0F9543B  1630761340         3  1630762641
 17       18  8.458990e+17     A0F9543B  1630763110         0  1630764706
 18       19  8.458990e+17     A0F9543B  1630764938         0  1630766136
 19       20  8.458990e+17     A0F9543B  1630766319         4  1630767331
 20       21  8.458990e+17     42E39272  1631194857         3  1631195672
 21       22  8.458990e+17     42E39272  1631195802         3  1631196953
 22       23  8.458990e+17     42E39272  1631197153         1  1631198326
 23       24  8.458990e+17     42E39272  1631198443         0  1631198648
 24       25  8.458990e+17     42E39272  1631198675         1  1631199444
 25       26  8.458990e+17     ECB58C7B  1631794733         0  1631796769
 26       27  8.458990e+17     ECB58C7B  1631797059         0  1631799181
 27       28  8.458990e+17     ECB58C7B  1631799582         3  1631801362
 28       29  8.458990e+17     ECB58C7B  1631801667         0  1631804296
 29       30  8.458990e+17     C7B8E367  1632399447         4  1632399624
 30       31  8.458990e+17     579FC1A2  1632399730         0  1632402227
 31       32  8.458990e+17     579FC1A2  1632402554         3  1632403769
 32       33  8.458990e+17     579FC1A2  1632404212         3  1632405408
 33       34  8.458990e+17     579FC1A2  1632405855         0  1632407187
 34       35  8.458990e+17     579FC1A2  1632407443         3  1632408154
 35       36  8.458990e+17     579FC1A2  1632408342         1  1632410072
 36       37  8.458990e+17     7A05B0E4  1632580081         0  1632580151
 37       38  8.458990e+17     7A05B0E4  1632580384         2  1632581463
 38       39  8.458990e+17     7A05B0E4  1632581633         0  1632582210
 39       40  8.458990e+17     7A05B0E4  1632582382         1  1632584017
 40       41  8.458990e+17     7A05B0E4  1632584208         4  1632585215
 41       42  8.458990e+17     7A05B0E4  1632585366         0  1632586713
 42       43  8.458990e+17     815344D3  1633003820         0  1633004852
 43       44  8.458990e+17     8E7AA202  1633005689         2  1633006409
 44       45  8.458990e+17     8E7AA202  1633006556         0  1633007593
 45       46  8.458990e+17     8E7AA202  1633007683         0  1633008217
 46       47  8.458990e+17     8E7AA202  1633008596        -1          -1
 47       48  8.458990e+17     C8A2626A  1633012312        -1          -1
 48       49  8.458990e+17     C8A2626A  1633012445         0  1633013746,
 'guilds':        guild_id guild_name  premium tx_time_unix
 0  8.458990e+17     ぱりーに農園        0         None,
 'users':          user_id   opt
 0   2.611571e+17  True
 1   3.896640e+17  True
 2   8.807449e+17  True
 3   3.411638e+17  True
 4   3.514106e+17  True
 5   6.318564e+17  True
 6   8.579729e+17  True
 7   3.401180e+17  True
 8   3.919258e+17  True
 9   3.143667e+17  True
 10  3.186218e+17  True
 11  3.506496e+17  True
 12  4.035556e+17  True
 13  3.962929e+17  True
 14  5.187324e+17  True
 15  8.732174e+17  True
 16  2.611572e+17  True,
 'users_games':           user_id      guild_id  game_id player_name  player_color  \
 0    2.611571e+17  8.458990e+17        1       shiki            12
 1    3.896640e+17  8.458990e+17        1         みふこ            13
 2    2.611571e+17  8.458990e+17        2       shiki            12
 3    3.896640e+17  8.458990e+17        2         みふこ            13
 4    2.611571e+17  8.458990e+17        3       shiki            12
 ..            ...           ...      ...         ...           ...
 274  8.807449e+17  8.458990e+17       49    Angrypan            14
 275  2.611571e+17  8.458990e+17       49       shiki            17
 276  3.143667e+17  8.458990e+17       49        tada             8
 277  3.186218e+17  8.458990e+17       49           け             2
 278  3.896640e+17  8.458990e+17       49         みふこ            13

      player_role  player_won
 0              1        True
 1              0       False
 2              0        True
 3              0        True
 4              1        True
 ..           ...         ...
 274            0        True
 275            1       False
 276            0        True
 277            0        True
 278            0        True

 [279 rows x 7 columns]}

In [77]:
games = df_dict_['games']

In [78]:
games[(games.loc[:, 'win_type'] == 0) | (games.loc[:, 'win_type'] == 1) | (games.loc[:, 'win_type'] == 6)].shape

(24, 6)

In [79]:
games.shape

(49, 6)

In [80]:
47-24

23

In [81]:
24/(24+23)

0.5106382978723404


[automuteus/storage/statsQueries.go](https://github.com/denverquane/automuteus/blob/7887a1b2b30d20e0a64fec69c48d04cff768066b/storage/statsQueries.go)

- Crewmate win: win_type = 0 or 1 or 6
- Imposter win: win_type = 2 or 3 or 4 or 5

```go
if role == game.CrewmateRole {
    err = pgxscan.Get(context.Background(), psqlInterface.Pool, &r, "SELECT COUNT(*) FROM games WHERE guild_id=$1 AND (win_type=0 OR win_type=1 OR win_type=6)", gid)
} else {
    err = pgxscan.Get(context.Background(), psqlInterface.Pool, &r, "SELECT COUNT(*) FROM games WHERE guild_id=$1 AND (win_type=2 OR win_type=3 OR win_type=4 OR win_type=5)", gid)
```