In [1]:
import ipywidgets as widgets
import pandas as pd
import numpy as np
import psycopg2
import bqplot

In [2]:
connection_config = {
    'user': 'postgres',
    'password': 'putsomesecretpasswordhere',
    'host': 'postgres',
    'port': '5432',
    'database': 'postgres',
}
connection_config

{'user': 'postgres',
 'password': 'putsomesecretpasswordhere',
 'host': 'postgres',
 'port': '5432',
 'database': 'postgres'}

In [13]:
sql = r'SELECT * FROM game_events;'


with psycopg2.connect(**connection_config) as conn:
    df = pd.read_sql_query(sql, conn)

pd.set_option("display.max_colwidth", 120)
df[df.iloc[:, -2] == 1]

,event_id,user_id,game_id,event_time,event_type,payload
4,6,NaN,1,1630586994,1,"{'Map': 0, 'Region': 0, 'LobbyCode': 'BKAUIF'}"
47,52,NaN,6,1630590215,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'YIZCHF'}"
86,98,NaN,12,1630593229,1,"{'Map': 4, 'Region': 1, 'LobbyCode': 'LWRYFF'}"
106,120,NaN,14,1630759016,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'KDKSDF'}"
168,182,NaN,17,1630762641,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'KDKSDF'}"
193,208,NaN,18,1630764706,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'HXONCF'}"
236,250,NaN,20,1630767331,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'HXONCF'}"
249,263,NaN,21,1631195672,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'HLSPNF'}"
272,286,NaN,22,1631196953,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'HLSPNF'}"
338,353,NaN,26,1631796769,1,"{'Map': 0, 'Region': 0, 'LobbyCode': 'CDHYVF'}"
406,422,NaN,28,1631801362,1,"{'Map': 0, 'Region': 0, 'LobbyCode': 'CDHYVF'}"
447,464,NaN,29,1631804296,1,"{'Map': 0, 'Region': 0, 'LobbyCode': 'CDHYVF'}"
453,470,NaN,30,1632399624,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
506,523,NaN,32,1632403769,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
526,544,NaN,33,1632405408,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
548,567,NaN,34,1632407187,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
561,581,NaN,35,1632408154,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
587,607,NaN,36,1632410072,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'ECQXNF'}"
613,633,NaN,38,1632581463,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
629,649,NaN,39,1632582210,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
630,672,NaN,40,1632584017,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
665,690,NaN,41,1632585215,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
694,719,NaN,42,1632586713,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'TYTBNF'}"
708,744,NaN,44,1633006409,1,"{'Map': 4, 'Region': 1, 'LobbyCode': 'JCYQKF'}"
736,764,NaN,45,1633007593,1,"{'Map': 4, 'Region': 1, 'LobbyCode': 'JCYQKF'}"
747,776,NaN,46,1633008217,1,"{'Map': 4, 'Region': 1, 'LobbyCode': 'JCYQKF'}"
758,787,NaN,48,1633012418,1,"{'Map': 0, 'Region': 1, 'LobbyCode': 'EDXSVF'}"